"""
ComicCraft PDF Generation Service
Uses fpdf2 and PIL to generate professional, multi-panel comic book PDFs.
Includes:
- Comic Title Cover / Header Banner with ComicCraft branding
- Sequential Panel Layouts with crisp comic borders
- High-resolution Panel Illustrations
- Narration Caption Box (Yellow comic caption styling)
- Character Dialogue Speech Balloons
- Metadata (Character, Setting, Tone, Art Style, AI Generation Timestamp)
- Running Page Numbers and Issue Watermark
"""

import os
import io
import time
import base64
import unicodedata
from typing import Dict, Any, List
from fpdf import FPDF
from PIL import Image, ImageDraw, ImageFont

PDF_OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "generated_pdfs")
os.makedirs(PDF_OUTPUT_DIR, exist_ok=True)


def sanitize_fpdf_text(text: str) -> str:
    """
    Sanitizes unicode characters for FPDF core Helvetica font:
    converts smart quotes, em-dashes, bullets, and accents into latin-1 safe ASCII.
    """
    if not text:
        return ""
    replacements = {
        "\u2022": "-",
        "\u2013": "-",
        "\u2014": "--",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u00a0": " ",
        "’": "'",
        "‘": "'",
        "“": '"',
        "”": '"',
        "—": "--",
        "–": "-",
        "•": "-"
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    # Normalize unicode and encode to latin-1 safely
    text = unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")
    return text


class ComicBookPDF(FPDF):
    def __init__(self, comic_title: str, character: str, setting: str, art_style: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.comic_title = sanitize_fpdf_text(comic_title)
        self.character = sanitize_fpdf_text(character)
        self.setting = sanitize_fpdf_text(setting)
        self.art_style = sanitize_fpdf_text(art_style)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Comic Top Bar on every page
        self.set_fill_color(17, 19, 24) # Charcoal near-black
        self.rect(0, 0, 210, 14, "F")
        
        # Yellow accent line
        self.set_fill_color(255, 230, 0) # Bright yellow
        self.rect(0, 14, 210, 1.5, "F")

        # Header branding
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(255, 230, 0)
        self.set_xy(10, 3)
        self.cell(50, 8, "COMICCRAFT", 0, 0, "L")

        self.set_font("Helvetica", "I", 8)
        self.set_text_color(240, 240, 240)
        self.set_xy(65, 3)
        self.cell(90, 8, f"{self.comic_title} - {self.art_style} Edition", 0, 0, "C")

        self.set_font("Helvetica", "", 8)
        self.set_text_color(200, 200, 200)
        self.set_xy(160, 3)
        self.cell(40, 8, "AI Studio Edition", 0, 0, "R")
        self.ln(12)

    def footer(self):
        self.set_y(-12)
        # Footer border line
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.4)
        self.line(10, 285, 200, 285)

        self.set_font("Helvetica", "", 8)
        self.set_text_color(120, 120, 120)
        self.set_xy(10, -10)
        self.cell(90, 8, "Generated by ComicCraft - AI Comic Story Creator", 0, 0, "L")
        self.set_xy(150, -10)
        self.cell(50, 8, f"Page {self.page_no()}", 0, 0, "R")


def _create_raster_panel_image(panel: Dict[str, Any], character: str, setting: str, art_style: str) -> str:
    """
    Renders or converts a panel illustration into a temporary PNG for embedding in FPDF.
    Handles data URI PNGs or synthesizes high-res raster panels with PIL.
    """
    temp_dir = os.path.join(PDF_OUTPUT_DIR, "temp_img")
    os.makedirs(temp_dir, exist_ok=True)
    temp_path = os.path.join(temp_dir, f"panel_{panel.get('number', 1)}_{int(time.time()*1000)}.png")

    img_data = panel.get("image", "")

    # If it's a base64 PNG, decode directly
    if img_data.startswith("data:image/png;base64,"):
        raw = base64.b64decode(img_data.split(",")[1])
        with open(temp_path, "wb") as f:
            f.write(raw)
        return temp_path

    # For SVGs or fallback, generate a clean high-resolution stylized comic panel bitmap using PIL
    width, height = 800, 480
    im = Image.new("RGB", (width, height), color=(17, 19, 24))
    draw = ImageDraw.Draw(im)

    # Style gradient / background
    style_colors = {
        "Anime": ((30, 27, 75), (236, 72, 153), (255, 75, 130)),
        "Comic Book": ((15, 23, 42), (245, 158, 11), (255, 230, 0)),
        "Cartoon": ((22, 78, 99), (56, 189, 248), (6, 182, 212)),
        "Pixel Art": ((2, 44, 34), (16, 185, 129), (52, 211, 153)),
        "Realistic": ((28, 25, 23), (120, 113, 108), (245, 158, 11)),
        "Manga": ((9, 9, 11), (39, 39, 42), (244, 244, 245)),
        "Fantasy": ((46, 16, 101), (147, 51, 234), (192, 132, 252))
    }
    bg_top, bg_mid, accent = style_colors.get(art_style, ((15, 23, 42), (30, 41, 59), (255, 230, 0)))

    # Draw vertical sky gradient
    for y in range(height):
        ratio = y / height
        r = int(bg_top[0] * (1 - ratio) + bg_mid[0] * ratio)
        g = int(bg_top[1] * (1 - ratio) + bg_mid[1] * ratio)
        b = int(bg_top[2] * (1 - ratio) + bg_mid[2] * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))

    # Sunburst / Energy orb
    draw.ellipse([width//2 - 120, 40, width//2 + 120, 280], fill=accent, outline=(255, 255, 255), width=2)

    # Silhouette terrain based on setting
    p_num = panel.get("number", 1)
    if setting in ["Enchanted Forest", "Medieval Kingdom"]:
        # Mountains / Trees
        draw.polygon([(0, height), (150, 260), (320, 340), (550, 220), (800, 360), (800, height)], fill=(10, 12, 16))
        draw.polygon([(80, height), (220, 200), (380, height)], fill=(20, 24, 33))
    elif setting in ["City", "Future World"]:
        # City Skyline
        draw.rectangle([40, 220, 160, height], fill=(10, 12, 16), outline=accent, width=1)
        draw.rectangle([180, 160, 320, height], fill=(6, 8, 12), outline=(255, 255, 255), width=1)
        draw.rectangle([340, 240, 480, height], fill=(15, 20, 28), outline=accent, width=1)
        draw.rectangle([500, 140, 640, height], fill=(8, 10, 14), outline=(255, 255, 255), width=1)
        draw.rectangle([660, 200, 780, height], fill=(10, 12, 16), outline=accent, width=1)
    else:
        # Space / Cosmic horizon
        draw.ellipse([60, height - 120, 740, height + 300], fill=(10, 14, 22), outline=accent, width=2)

    # Character Silhouette & Action Aura
    cx = 400 + (p_num * 20 - 60)
    cy = 340
    # Aura
    draw.ellipse([cx - 45, cy - 100, cx + 45, cy], fill=None, outline=accent, width=3)
    # Cloak / Body
    draw.polygon([(cx - 30, cy), (cx + 30, cy), (cx + 15, cy - 65), (cx - 15, cy - 65)], fill=(12, 14, 18))
    # Head
    draw.ellipse([cx - 15, cy - 95, cx + 15, cy - 65], fill=(12, 14, 18), outline=(255, 255, 255), width=1)
    # Glowing eyes
    draw.line([(cx - 7, cy - 80), (cx - 2, cy - 80)], fill=(255, 255, 255), width=2)
    draw.line([(cx + 2, cy - 80), (cx + 7, cy - 80)], fill=(255, 255, 255), width=2)

    # Thick Comic Panel Frame Border
    draw.rectangle([6, 6, width - 6, height - 6], outline=(17, 19, 24), width=8)
    draw.rectangle([12, 12, width - 12, height - 12], outline=accent, width=2)

    # Panel Stamp Tag
    draw.rectangle([25, 25, 220, 60], fill=(17, 19, 24), outline=(255, 230, 0), width=2)
    draw.text((35, 33), f"PANEL 0{p_num}: {sanitize_fpdf_text(panel.get('title', 'SCENE')).upper()[:18]}", fill=(255, 230, 0))

    # Art Style Badge
    draw.rectangle([width - 180, 25, width - 25, 60], fill=(17, 19, 24), outline=(255, 255, 255), width=1)
    draw.text((width - 170, 33), f"{art_style.upper()} ART", fill=(255, 255, 255))

    im.save(temp_path, "PNG")
    return temp_path


def generate_comic_pdf(comic_data: Dict[str, Any]) -> str:
    """
    Builds the complete ComicCraft comic book PDF document and saves to disk.
    Returns the absolute path to the generated PDF.
    """
    raw_title = comic_data.get("title", "ComicCraft Adventure")
    title = sanitize_fpdf_text(raw_title)
    character = sanitize_fpdf_text(comic_data.get("character", "Hero"))
    setting = sanitize_fpdf_text(comic_data.get("setting", "World"))
    tone = sanitize_fpdf_text(comic_data.get("tone", "Adventure"))
    art_style = sanitize_fpdf_text(comic_data.get("art_style", "Comic Book"))
    panels = comic_data.get("panels", [])

    safe_title = "".join(c for c in title if c.isalnum() or c in ("-", "_")).rstrip()
    pdf_filename = f"ComicCraft_{safe_title}_{int(time.time())}.pdf"
    pdf_path = os.path.join(PDF_OUTPUT_DIR, pdf_filename)

    pdf = ComicBookPDF(
        comic_title=title,
        character=character,
        setting=setting,
        art_style=art_style
    )

    # --- COVER / TITLE BANNER PAGE ---
    pdf.add_page()

    # Title Hero Card
    pdf.set_fill_color(245, 247, 250)
    pdf.set_draw_color(17, 19, 24)
    pdf.set_line_width(1.0)
    pdf.rect(10, 20, 190, 42, "FD")

    # Comic Title Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(17, 19, 24)
    pdf.set_xy(15, 24)
    pdf.multi_cell(180, 8, title.upper(), 0, "C")

    # Issue metadata pill row
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(90, 90, 90)
    pdf.set_xy(15, 46)
    meta_line = f"PROTAGONIST: {character.upper()}  |  SETTING: {setting.upper()}  |  TONE: {tone.upper()}  |  STYLE: {art_style.upper()}"
    pdf.cell(180, 6, meta_line, 0, 1, "C")

    # --- PANELS LAYOUT (2 panels per page for spacious, clean comic presentation) ---
    temp_images_to_clean = []
    
    current_y = 68
    for idx, panel in enumerate(panels):
        # Add new page after every 2 panels (or when page exceeds)
        if idx > 0 and idx % 2 == 0:
            pdf.add_page()
            current_y = 20

        p_num = panel.get("number", idx + 1)
        p_title = sanitize_fpdf_text(panel.get("title", f"Panel {p_num}"))
        caption = sanitize_fpdf_text(panel.get("caption", ""))
        dialogue = sanitize_fpdf_text(panel.get("dialogue", ""))

        # Panel Container Box
        panel_height = 100
        pdf.set_fill_color(255, 255, 255)
        pdf.set_draw_color(17, 19, 24)
        pdf.set_line_width(0.8)
        pdf.rect(10, current_y, 190, panel_height, "FD")

        # Panel Header Banner
        pdf.set_fill_color(17, 19, 24)
        pdf.rect(10, current_y, 190, 7.5, "F")
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(255, 230, 0) # Comic yellow
        pdf.set_xy(14, current_y + 1)
        pdf.cell(120, 5.5, f"PANEL 0{p_num}: {p_title.upper()}", 0, 0, "L")

        # Embed Panel Image
        img_temp_path = _create_raster_panel_image(panel, character, setting, art_style)
        temp_images_to_clean.append(img_temp_path)

        # Image placement on left (width: 90mm, height: 54mm)
        img_x = 14
        img_y = current_y + 10
        img_w = 90
        img_h = 54
        pdf.image(img_temp_path, x=img_x, y=img_y, w=img_w, h=img_h)
        # Comic frame border around image
        pdf.set_draw_color(17, 19, 24)
        pdf.set_line_width(0.6)
        pdf.rect(img_x, img_y, img_w, img_h)

        # Right side: Narration Caption Box & Dialogue Bubble
        text_x = 108
        text_w = 88

        # 1. Narration Caption Box (Comic Yellow)
        pdf.set_fill_color(255, 250, 205) # Pale yellow comic caption
        pdf.set_draw_color(17, 19, 24)
        pdf.set_line_width(0.4)
        pdf.rect(text_x, img_y, text_w, 24, "FD")

        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(160, 110, 0)
        pdf.set_xy(text_x + 2, img_y + 1.5)
        pdf.cell(text_w - 4, 3.5, "NARRATION:", 0, 1, "L")

        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(20, 20, 20)
        pdf.set_xy(text_x + 2, img_y + 5.5)
        pdf.multi_cell(text_w - 4, 4, f'"{caption}"', 0, "L")

        # 2. Dialogue Speech Balloon Box
        diag_y = img_y + 27
        pdf.set_fill_color(255, 255, 255)
        pdf.set_draw_color(30, 41, 59)
        pdf.set_line_width(0.5)
        pdf.rect(text_x, diag_y, text_w, 27, "FD")

        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(37, 99, 235) # Electric blue header
        pdf.set_xy(text_x + 2, diag_y + 1.5)
        pdf.cell(text_w - 4, 3.5, "CHARACTER DIALOGUE:", 0, 1, "L")

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(15, 23, 42)
        pdf.set_xy(text_x + 2, diag_y + 5.5)
        clean_diag = dialogue if dialogue else f'{character.upper()}: "..."'
        pdf.multi_cell(text_w - 4, 4, clean_diag, 0, "L")

        # Bottom scene description footer inside panel
        pdf.set_fill_color(248, 250, 252)
        pdf.rect(10, current_y + 68, 190, 30, "F")
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(100, 116, 139)
        pdf.set_xy(14, current_y + 70)
        scene_txt = sanitize_fpdf_text(panel.get('scene_description', ''))[:140]
        pdf.cell(180, 4, f"Visual Setting: {scene_txt}", 0, 1, "L")
        pdf.set_xy(14, current_y + 75)
        pdf.set_font("Helvetica", "I", 6.5)
        prompt_txt = sanitize_fpdf_text(panel.get('image_prompt', ''))[:150]
        pdf.cell(180, 4, f"Generative Prompt: {prompt_txt}...", 0, 1, "L")

        # Advance to next panel position
        current_y += panel_height + 6

    # Output PDF
    pdf.output(pdf_path)

    # Clean up temporary raster images
    for p in temp_images_to_clean:
        try:
            if os.path.exists(p):
                os.remove(p)
        except Exception:
            pass

    return pdf_path
